version: "3.5"

networks:
  lost-horizon-frontend:
    driver: bridge

services:
  dashboard:
    container_name: dashboard
    image: ${DOCKER_IMAGE}:${VERSION}
    environment:
      - CHOKIDAR_USEPOLLING="true"
      - REACT_APP_VERSION=${VERSION}
      - REACT_APP_NAME=lost-horizon
      - REACT_APP_API_URL=${API_ENDPOINT}
      - NGINX_API_URL=http://localhost:4000
      - NGINX_PORT=80 # 443 for HTTPS eventually
    # depends_on: # Eventually
    #   - api
    networks:
      - lost-horizon-frontend
    ports:
      - 3000:80
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true